import {
  BookOpen,
  Bot,
  Briefcase,
  Building2,
  Calculator,
  ClipboardList,
  File,
  FileArchive,
  FileAudio,
  FileCode,
  FileEdit,
  FileImage,
  FilePen,
  FilePlus,
  FileSearch,
  FileSignature,
  FileSpreadsheet,
  FileStack,
  FileText,
  FileType,
  FileVideo,
  Folder,
  FolderOpen,
  FolderSearch,
  Globe,
  GraduationCap,
  HeartHandshake,
  Landmark,
  Lightbulb,
  Mail,
  MessageCircleQuestion,
  MessagesSquare,
  Newspaper,
  PenTool,
  Scale,
  Search,
  Sheet,
  ShoppingCart,
  Sparkles,
  Users,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const REGISTRY: Record<string, LucideIcon> = {
  BookOpen,
  Bot,
  Briefcase,
  Building2,
  Calculator,
  ClipboardList,
  File,
  FileArchive,
  FileAudio,
  FileCode,
  FileEdit,
  FileImage,
  FilePen,
  FilePlus,
  FileSearch,
  FileSignature,
  FileSpreadsheet,
  FileStack,
  FileText,
  FileType,
  FileVideo,
  Folder,
  FolderOpen,
  FolderSearch,
  Globe,
  GraduationCap,
  HeartHandshake,
  Landmark,
  Lightbulb,
  Mail,
  MessageCircleQuestion,
  MessagesSquare,
  Newspaper,
  PenTool,
  Scale,
  Search,
  Sheet,
  ShoppingCart,
  Sparkles,
  Users,
  Wrench,
};

/** Curated subset offered in the agent editor's icon picker. Every entry
 *  must exist in REGISTRY — the picker renders through DynamicIcon. */
export const AGENT_ICON_CHOICES: string[] = [
  "Bot",
  "Briefcase",
  "Building2",
  "Calculator",
  "ClipboardList",
  "FileText",
  "FileSpreadsheet",
  "FolderSearch",
  "Globe",
  "Lightbulb",
  "Mail",
  "PenTool",
  "Scale",
  "ShoppingCart",
  "Users",
  "BookOpen",
];

type Props = {
  name: string | null | undefined;
  fallback?: LucideIcon;
  className?: string;
};

/** Renders a Lucide icon resolved from a stored string name (e.g. skill/agent icon fields). */
export function DynamicIcon({ name, fallback = Bot, className }: Props) {
  const Icon = (name && REGISTRY[name]) || fallback;
  return <Icon className={className} />;
}
